name: Build and Release Node.js Project

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Get version from package.json
        id: get-version
        run: echo "PACKAGE_VERSION=$(cat package.json | jq -r .version)" >> "$GITHUB_ENV"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Install dependencies and build
        run: npm ci && npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: index-macos
          path: index-macos

      - name: Set PACKAGE_VERSION
        run: echo "::set-env name=PACKAGE_VERSION::$(cat package.json | jq -r .version)"

      - name: Create a release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.AUTOCI }}
        with:
          tag_name: ${{ env.PACKAGE_VERSION }}
          release_name: Release of ${{ env.PACKAGE_VERSION }}
          draft: false
          prerelease: false
          artifact_paths: index-macos
